#!/bin/bash
echo "Script 1"
diff <(ls *.jpg | cut -d. -f1) <(ls *.txt | cut -d. -f1) | grep '^[<>]' | tr -d '< ' | tr -d '> '
echo "Script 2"
ls *.{jpg,txt} \
| sed 's/\.[^.]*$//' \
| uniq -c
echo "Script 3"
ls *.{jpg,txt} \
| sed 's/\.[^.]*$//' \
| uniq -c \
| awk '/^ *1 /{print $2 "*"}'
exit 0

